export const loginTypes = {
    LOGIN_USER: 'LOGIN_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    CREATE_USER: 'CREATE_USER',
    GET_USER: 'GET_USER',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    TOGGLE_LOGIN: 'TOGGLE_LOGIN',
    UPDATE_USER: 'UPDATE_USER'
}