export const productTypes = {
    PRODUCTS_GET: 'PRODUCTS_GET',
    PRODUCTS_FILTERED: 'PRODUCTS_FILTERED',
    PRODUCTS_CREAT: 'PRODUCTS_CREAT',
    PRODUCTS_DELET: 'PRODUCTS_DELET',
    PRODUCTS_EDIT: 'PRODUCTS_EDIT',
    NEW_PRODUCTS: 'NEW_PRODUCTS',
    PRODUCTS_FILTERED_BY_SEARCH: 'PRODUCTS_FILTERED_BY_SEARCH'
    }